# Generated by Django 5.1.1 on 2024-11-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_alter_cv_git_link_alter_cv_linkedin_link'),
        ('Fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvPerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.cv')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fields.fields')),
            ],
        ),
    ]
