# Generated by Django 5.1.1 on 2024-11-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyCard', '0001_initial'),
        ('Fields', '0002_cvperfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCardPerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyCard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyCard.companycard')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fields.fields')),
            ],
        ),
    ]
