# Generated by Django 5.1.1 on 2024-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('required_level', models.CharField(default='')),
                ('position_type', models.CharField(default='')),
                ('date_publication', models.DateField(auto_now=True)),
                ('contenu', models.CharField(max_length=255, null=True)),
                ('is_checked', models.BooleanField(default=True)),
                ('places_disponibles', models.IntegerField()),
                ('type_announce', models.BooleanField(default=False)),
                ('address', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncePerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postule', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillPerAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
