# Generated by Django 5.1.1 on 2024-11-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
