# Generated by Django 5.1.1 on 2024-11-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillPerCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.cv')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skills.skill')),
            ],
        ),
    ]
