# Generated by Django 5.1.1 on 2024-11-16 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_level', models.CharField(default='')),
                ('salary', models.IntegerField(default=0)),
                ('bio', models.CharField(default='')),
                ('git_link', models.URLField(blank=True, null=True)),
                ('linkedIn_link', models.URLField(blank=True, null=True)),
                ('x_link', models.CharField(blank=True, null=True)),
                ('portfolio_link', models.CharField(blank=True, null=True)),
                ('soft_life_description', models.CharField(max_length=255)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('current', models.BooleanField()),
                ('cv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('cv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.cv')),
            ],
        ),
    ]
