# Generated by Django 5.1.1 on 2024-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='git_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='linkedIn_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
